#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {model_name}
spec:
  selector:
    matchLabels:
      app: {model_name}
  replicas: 1
  template:
    metadata:
      labels:
        app: {model_name}
    spec:
      containers:
      - name: {model_name}
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/{docker_user}/{model_name}:{github.sha}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {model_name}
  name: {model_name}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: {model_name}
  type: LoadBalancer
